services:
  server:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/cringy-blog
      - GELF_ADDR=localhost:12201
  postgres:
    image: ubuntu/postgres:latest
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cringy-blog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5
